class Material:
    def __doc__(self) -> str: ...
    def __get_data(self, args: tuple) -> any: ...
    def __init__(self) -> None: ...
    def __del__(self) -> bool: ...
    def __str__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __to_tuple__(self) -> tuple: ...
    def __to_list__(self) -> list: ...
    def __to_dict__(self) -> dict: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int | str: ...
    def __setitem__(self, index: int, value: int) -> None: ...
    def __delitem__(self, index: int) -> None: ...
    def __add__(self, args: tuple) -> any: ...
    def __sub__(self, args: tuple) -> any: ...
    def __iadd__(self, args: tuple) -> any: ...
    def __isub__(self, args: tuple) -> any: ...
    def __lt__(self, args: tuple) -> tuple[bool, bool, bool]: ...
    def __le__(self, args: tuple) -> tuple[bool, bool, bool]: ...
    def __gt__(self, args: tuple) -> tuple[bool, bool, bool]: ...
    def __ge__(self, args: tuple) -> tuple[bool, bool, bool]: ...
    def __eq__(self, args: tuple) -> tuple[bool, bool, bool]: ...
    def __ne__(self, args: tuple) -> tuple[bool, bool, bool]: ...


class Inventory:
    def __doc__(self) -> str: ...
    def __init__(self) -> None: ...
    def __del__(self) -> bool: ...
    def __str__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __getitem__(self, Material_Type: str) -> any: ...
    def __setitem__(self, Material_Type: str,
                    index: int, value: int) -> None: ...

    def __delitem__(self, Material_Type: str) -> any: ...
    def Update(self,  mark: str, value: int,
               parametr: str | None = None) -> None: ...

    def Reset(self, mark: str, parametr: str | None = None) -> None: ...


class Character:
    def __doc__(self) -> str: ...
    def __init__(self, name: str, path: str) -> None: ...
    def __del__(self) -> bool: ...
    def __str__(self) -> str: ...
    def __bool__(self) -> bool: ...
    def __getitem__(self, mark: str) -> any: ...
    def __setitem__(self, mark: str, value: int) -> None: ...
    def __delitem__(self, mark: str) -> None: ...
    def Change(self, mark: str, value: int | str,
               parametr: str | int = None) -> None: ...

    def Reset(self, mark: str, parametr: str | int = None) -> None: ...


class Calculate:
    def __get_line(self, num: bool = False) -> tuple[str]: ...
    def __doc__(self) -> str: ...
    def __init__(self, character: Character, inventory: Inventory) -> None: ...
    def __del__(self) -> None: ...
    def __str__(self) -> str: ...
    def UpdateInventory(self) -> None: ...
    def UpdateCharacter(self) -> None: ...
    def ChangeCharacter(self): ...
    def DeleteCharacter(self): ...
